### ISSUE TITLE
Misspelling in location

### ISSUE THREAD

**Issue by smarziano** [sariyie/mRelief#3]
During CUTGroup testing, a tester noticed there was a misspelling in the location "Englewood Community Service Center." The current spelling is "Englewod"

![screen shot 2015-02-24 at 7 54 39 pm](https://cloud.githubusercontent.com/assets/5550969/6363523/fdefde90-bc5f-11e4-8839-7f8b65cc0cdf.png)

**Comment by genevievenielsen** [comment]
Thank you so much Sonja for letting us know! It is fixed now :)
